const boatItem= [
    {
    id: 1,
    name: 'Airpods 131',
    category : 'airpods',
    rating : '4.8  |  1336',
    price: 899,
    originalprice: 2990,
    offer: 70,
    img: './images/Airpods.jpg',
    hours: '60 Hours Playback',
    quantity: 1
},
{
    id: 2,
    name: 'Airpods 161',
    name1: 'fd',
    category : 'airpods',
    rating : '4.9  |  149',
    price: 999,
    originalprice: 2490,
    offer: 60,
    img: './images/Airpods161.jpg',
    hours: '40 Hours Playback',
    quantity: 1
},

{
    id: 3,
    name: 'Rockerz 235 V2',
    category : 'airpods',
    rating : '4.8  |  1074',
    price: 999,
    originalprice: 2490,
    offer: 67,
    img: './images/rockerz-235-v2.jpg',
    hours: '8 Hours Playback',
    quantity: 1
},
{
    id: 4,
    name: 'Airpods 121',
    category : 'airpods',
    rating : '4.9  |  648',
    price: 1299,
    originalprice: 4490,
    offer: 71,
    img: './images/Airpods121.jpg',
    hours: '42 Hours Playback',
    quantity: 1
},
{
    id: 5,
    name: 'Stone Majestic Riverdale Rocker',
    category : 'newlaunches',
    rating : '4.8 | 10',
    price: 9999,
    originalprice: 2999,
    offer: 88,
    img: 'images/Stone_Archies.jpg',
    hours: '60 Hours Playback',
    quantity: 1
},
{
    id: 6,
    name: 'Aavante Bar',
    category : 'newlaunches',
    rating : '4.8 | 55',
    price: 2199,
    originalprice: 2999,
    offer: 88,
    img: 'images/Aavante_Bar-558.jpg',
    hours: '16W RMS Sound',
    quantity: 1
},
{
    id: 7,
    name: 'Lunar_Tigo',
    category : 'newlaunches',
    rating : '4.8 | 810',
    price: 2899,
    originalprice: 2999,
    offer: 88,
    img: 'images/Lunar_Tigon.gif',
    hours: 'BT Calling',
    quantity: 1
},
{
    id: 8,
    name: 'Stone 750',
    category : 'newlaunches',
    rating : '4.8 | 48',
    price: 2199,
    originalprice: 2999,
    offer: 88,
    img: 'images/Stone_750.jpg',
    hours: '12 Hours Playback',
    quantity: 1
},
{
    id: 9,
    name: 'Aavante Bar 1150',
    category : 'soundbars',
    rating : '5.0 | 1',
    price: 5299,
    originalprice: 9999,
    offer: 47,
    img: 'images/aavante-bar-1160.jpg',
    hours: '60W Rms Sound',
    quantity: 1
},
{
    id: 10,
    name: 'Aavante Bar Rhythm',
    category : 'soundbars',
    rating : '4.8 | 8',
    price: 4999,
    originalprice: 9999,
    offer: 37,
    img: 'images/Aavante_bar_rhythm.jpg',
    hours: '60W Rms Sound',
    quantity: 1
},
{
    id: 11,
    name: 'Aavante Bar',
    category : 'soundbars',
    rating : '4.8 | 8',
    price: 1299,
    originalprice: 3490,
    offer: 63,
    img: 'images/Aavante_bar.jpg',
    hours: '10W Rms Sound',
    quantity: 1
},
{
    id: 12,
    name: 'Aavante Bar 500',
    category : 'soundbars',
    rating : '4.9 | 7',
    price: 1799,
    originalprice: 2490,
    offer: 40,
    img: 'images/Aavante_bar_500.jpg',
    hours: '16W Rms Sound',
    quantity: 1
},
{
    id: 13,
    name: 'Dual Charger with cable',
    category : 'accessories',
    rating : '4.7 | 5',
    price: 599,
    originalprice: 1499,
    offer: 60,
    img: 'images/qc-pd_main_mu.jpg',
    quantity: 1
},
{
    id: 14,
    name: 'Dual Rapid QC 3.0NC',
    category : 'accessories',
    rating : '4.8 | 2',
    price: 599,
    originalprice: 1499,
    offer: 60,
    img: 'images/car-charger.jpg',
    hours: 'QUICK Charger 3.0',
    quantity: 1
},
{
    id: 15,
    name: 'Dual Rapid QC 3.0NC',
    category : 'accessories',
    rating : '4.8 | 2',
    price: 499,
    originalprice: 899,
    offer: 33,
    img: 'images/car-charger.jpg',
    hours: 'QUICK Charger 3.0',
    quantity: 1
},
{
    id: 16,
    name: 'Dual QC-PD Rapid',
    category : 'accessories',
    rating : '4.2 | 50',
    price: 499,
    originalprice: 1499,
    offer: 67,
    img: 'images/qc-pd.jpg',
    hours: '18W Fast Charger',
    quantity: 1
},
{
    id: 17,
    name: 'Wave Call',
    category : 'top watches',
    rating : '4.9 | 49',
    price: 1699,
    originalprice: 7990,
    offer: 79,
    img: 'images/Wave_Call.jpg',
    hours: 'BT Calling',
    quantity: 1
},
{
    id: 18,
    name: 'Lunar Connect',
    category : 'top watches',
    rating : '4.9 | 15',
    price: 1799,
    originalprice: 7990,
    offer: 78,
    img: 'images/Lunar_Connect.jpg',
    hours: 'BT Calling',
    quantity: 1
},
{
    id: 19,
    name: 'Storm Call',
    category : 'top watches',
    rating : '4.8 | 27',
    price: 1499,
    originalprice: 7990,
    offer: 81,
    img: 'images/Storm_Call.jpg',
    hours: 'BT Calling',
    quantity: 1
},
{
    id: 20,
    name: 'Wave Beat',
    category : 'top watches',
    rating : '4.9 | 43',
    price: 2999,
    originalprice: 5990,
    offer: 50,
    img: 'images/Wave_Beat.jpg',
    hours: 'Activity Tracker',
    quantity: 1
},
]

export {boatItem};